[project]
name = "xtts2-ui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
    "gradio==6.3.0",
    "soundfile==0.12.1",
    "tts==0.22.0",
]
